name: data_annotation
description: Data annotation is used to transform an abstract class into an immutable data class with data_builder
version: 1.0.1
homepage: https://vegasdevelopments.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
